CREATE TABLE "PATIENT"
(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "SURNAME" VARCHAR(50) NOT NULL,
    "PATRONYMIC" VARCHAR(50) NOT NULL,
    "PHONE" VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID")
);
CREATE TABLE "DOCTOR"
(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(50) NOT NULL,
    "SURNAME" VARCHAR(50) NOT NULL,
    "PATRONYMIC" VARCHAR(50) NOT NULL,
    "SPECIALIZATION" VARCHAR(50) NOT NULL,
    CONSTRAINT "DOCTOR_PK" PRIMARY KEY ("ID")
);
CREATE TABLE "RECIPE"
(
    "ID" BIGINT NOT NULL,
    "DOCTOR" BIGINT NOT NULL,
    "PATIENT" BIGINT NOT NULL,
    "DESCRIPTION" VARCHAR(255) NOT NULL,
    "DATE" DATE NOT NULL,
    "VALIDITY" DOUBLE NOT NULL,
    "PRIORITY" VARCHAR(255) NOT NULL,
    CONSTRAINT "RECIPE_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_DOCTOR" FOREIGN KEY ("DOCTOR") REFERENCES "DOCTOR" ("ID") ON DELETE RESTRICT ,
    CONSTRAINT "FK_PATIENT" FOREIGN KEY ("PATIENT") REFERENCES "PATIENT" ("ID") ON DELETE RESTRICT
);


